spring.application.name=finanzas-api
spring.application.name=finanzas-api

spring.datasource.url=jdbc:mysql://localhost:3306/mjlc_finanzas?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MysQL#2026!Secure

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080